/** @type {import('tailwindcss').Config} */

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  safelist: [
    "text-red-500",
    "text-green-500",
    "text-orange-500",
    "text-yellow-500",
    "text-green-500",
    "bg-red-500",
    "bg-orange-500",
    "bg-yellow-500",
    "bg-green-500",
    "bg-black",
    "mx-[1.5px]",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        accent: {
          50: "#F4F2FF",
          100: "#E8E5FE",
          200: "#CFC8FD",
          300: "#B2A5FD",
          400: "#8F7AFC",
          500: "#612FFB",
          600: "#4B24C2",
          700: "#3D1E9F",
          800: "#2B1570",
          900: "#1F0F50",
          950: "#130932",
          1000: "#0C0620",
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        neutral: {
          50: "#F9F8FA",
          100: "#F3F2F5",
          200: "#E8E8EC",
          300: "#D6D5DD",
          400: "#C0BCC9",
          500: "#A6A0B2",
          600: "#958CA1",
          700: "#7F768B",
          800: "#6B6374",
          900: "#585260",
          950: "#3A3540",
        },
        success: {
          50: "#F0FBEA",
          100: "#DEF5D2",
          200: "#BEEDA9",
          300: "#96DF77",
          400: "#71CE4D",
          500: "#4FAE2D",
          600: "#3D8F21",
          700: "#306D1E",
          800: "#2A571D",
          900: "#254B1C",
          950: "#10280B",
        },
        warning: {
          50: "#FFF9ED",
          100: "#FFF2D5",
          200: "#FFE0A9",
          300: "#FEC973",
          400: "#FDA73A",
          500: "#FB8B13",
          600: "#EC6F0A",
          700: "#C4540A",
          800: "#9B4211",
          900: "#7D3911",
          950: "#441B06",
        },
        error: {
          50: "#FFF1F1",
          100: "#FFE1E1",
          200: "#FFC7C7",
          300: "#FFA1A1",
          400: "#FF6A6A",
          500: "#F73C3C",
          600: "#E01A1A",
          700: "#C11414",
          800: "#9F1515",
          900: "#841818",
          950: "#480707",
        },
      },
      backgroundColor: (theme) => ({
        ...theme("colors.accent"),
        ...theme("colors.neutral"),
        ...theme("colors.success"),
        ...theme("colors.warning"),
        ...theme("colors.error"),
        button: theme("colors.button"),
        modal: theme("colors.modal"),
      }),

      textColor: (theme) => ({
        ...theme("colors.accent"),
        ...theme("colors.neutral"),
        ...theme("colors.success"),
        ...theme("colors.warning"),
        ...theme("colors.error"),
      }),
      borderColor: (theme) => ({
        ...theme("colors.accent"),
        ...theme("colors.neutral"),
        ...theme("colors.success"),
        ...theme("colors.warning"),
        ...theme("colors.error"),
      }),

      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
